events {}
http {
  upstream docker { server docker-socket-proxy:2375; }
  server {
    listen 2375;
    location ~ ^/v1\.[0-9]+/(.*)$ {
      proxy_pass http://docker/v1.48/$1$is_args$args;
      proxy_http_version 1.1;
    }
    location / {
      proxy_pass http://docker;
      proxy_http_version 1.1;
    }
  }
}
